// LIFE App Static Data

import type { Pillar, Exercise } from './types';

export const INTENTIONS = [
  { id: 'presencia', label: 'Presencia', description: 'Estar más aquí, ahora' },
  { id: 'calma', label: 'Calma', description: 'Encontrar paz interior' },
  { id: 'claridad', label: 'Claridad', description: 'Pensar con más lucidez' },
  { id: 'vinculos', label: 'Vínculos', description: 'Conectar mejor con otros' },
  { id: 'orden', label: 'Orden', description: 'Organizar la vida diaria' },
] as const;

export const PILLARS: Pillar[] = [
  {
    id: 1,
    name: 'Reconocer el automático',
    description: 'Identificar los momentos donde actúas sin pensar, donde el cuerpo hace mientras la mente está en otro lugar.',
    exercise: 'Durante 5 minutos, observa tus manos mientras haces algo cotidiano. Solo observa.',
    realAction: 'Hoy, antes de tomar el celular, haz una pausa de 3 respiraciones.',
    completed: false,
    completedDates: [],
  },
  {
    id: 2,
    name: 'Elegir con conciencia',
    description: 'Entre el estímulo y la respuesta hay un espacio. En ese espacio está tu poder de elegir.',
    exercise: 'Cierra los ojos. Visualiza una situación donde sueles reaccionar. Imagina eligiendo diferente.',
    realAction: 'Ante una situación difícil hoy, cuenta hasta 5 antes de responder.',
    completed: false,
    completedDates: [],
  },
  {
    id: 3,
    name: 'Observar pensamientos',
    description: 'Los pensamientos no son hechos. Son nubes que pasan. Puedes observarlos sin engancharte.',
    exercise: 'Siéntate 5 minutos. Imagina tus pensamientos como hojas flotando en un río. Déjalos pasar.',
    realAction: 'Cuando notes un pensamiento crítico, di internamente: "Eso es solo un pensamiento".',
    completed: false,
    completedDates: [],
  },
  {
    id: 4,
    name: 'Habitar el cuerpo',
    description: 'Tu cuerpo es tu casa. Volver a él es volver a ti. La presencia empieza en las sensaciones físicas.',
    exercise: 'Escaneo corporal: Recorre tu cuerpo de pies a cabeza, notando sensaciones sin juzgar.',
    realAction: 'Tres veces hoy, pregunta: ¿Dónde siento tensión? Respira hacia ese lugar.',
    completed: false,
    completedDates: [],
  },
  {
    id: 5,
    name: 'Aceptar lo que es',
    description: 'Resistir lo que ya ocurrió consume energía. Aceptar no es aprobar, es reconocer la realidad.',
    exercise: 'Piensa en algo que te moleste. Respira y repite: "Esto es lo que hay. Puedo trabajar desde aquí".',
    realAction: 'Ante una frustración, en lugar de quejarte, pregunta: ¿Qué puedo hacer ahora?',
    completed: false,
    completedDates: [],
  },
  {
    id: 6,
    name: 'Cuidar el cuerpo',
    description: 'El cuerpo cansado, hambriento o sedentario es más vulnerable. Cuidarlo es cuidar tu mente.',
    exercise: 'Estiramiento consciente: 5 minutos moviendo el cuerpo lentamente, sintiendo cada movimiento.',
    realAction: 'Hoy, elige una comida consciente: sin pantallas, masticando despacio.',
    completed: false,
    completedDates: [],
  },
  {
    id: 7,
    name: 'Conectar con otros',
    description: 'El aislamiento amplifica lo que queremos evitar. La conexión genuina es sanadora.',
    exercise: 'Piensa en alguien importante. Envíale mentalmente buenos deseos durante 2 minutos.',
    realAction: 'Hoy, llama o escribe a alguien solo para saber cómo está, sin pedir nada.',
    completed: false,
    completedDates: [],
  },
  {
    id: 8,
    name: 'Reparar vínculos',
    description: 'Las relaciones rotas pesan. Reparar lo que puedas te libera, aunque no sea perfecto.',
    exercise: 'Piensa en una relación dañada. Sin juzgarte, pregúntate: ¿Qué parte fue mía?',
    realAction: 'Si es posible, ofrece una disculpa genuina hoy. O acepta una que no pediste.',
    completed: false,
    completedDates: [],
  },
  {
    id: 9,
    name: 'Agradecer',
    description: 'La gratitud cambia el foco. No niega los problemas, pero ilumina lo que sí funciona.',
    exercise: 'Escribe tres cosas por las que estés agradecido hoy. Pequeñas o grandes.',
    realAction: 'Agradece en voz alta a alguien por algo específico.',
    completed: false,
    completedDates: [],
  },
  {
    id: 10,
    name: 'Servir',
    description: 'Hacer algo por otro sin esperar nada te saca del centro. Y paradójicamente, te llena.',
    exercise: 'Reflexiona: ¿A quién podrías ayudar hoy? ¿Qué pequeño acto serviría?',
    realAction: 'Realiza un acto de servicio sin que te lo pidan y sin contarlo.',
    completed: false,
    completedDates: [],
  },
  {
    id: 11,
    name: 'Soltar el control',
    description: 'No puedes controlar todo. Soltar lo que no depende de ti es libertad.',
    exercise: 'Haz una lista de lo que te preocupa. Separa lo que puedes influir de lo que no. Suelta lo segundo.',
    realAction: 'Ante algo fuera de tu control hoy, di: "Esto no me corresponde resolver".',
    completed: false,
    completedDates: [],
  },
  {
    id: 12,
    name: 'Vivir el día',
    description: 'El único momento real es este. El pasado ya fue, el futuro no existe. Vive hoy.',
    exercise: 'Durante 5 minutos, haz algo cotidiano con atención plena: caminar, beber agua, mirar el cielo.',
    realAction: 'Cada vez que notes tu mente en el pasado o futuro, vuelve suavemente al ahora.',
    completed: false,
    completedDates: [],
  },
];

export const EXERCISES: Exercise[] = [
  {
    id: 'respiracion-4-7-8',
    name: 'Respiración 4-7-8',
    duration: '3 min',
    description: 'Una técnica simple para calmar el sistema nervioso.',
    steps: [
      'Siéntate cómodo con la espalda recta',
      'Inhala por la nariz contando hasta 4',
      'Mantén el aire contando hasta 7',
      'Exhala por la boca contando hasta 8',
      'Repite 4 veces',
    ],
    type: 'respiracion',
  },
  {
    id: 'escaneo-corporal',
    name: 'Escaneo corporal',
    duration: '5 min',
    description: 'Recorre tu cuerpo con atención, notando sensaciones.',
    steps: [
      'Acuéstate o siéntate cómodo',
      'Cierra los ojos',
      'Comienza por los pies, nota las sensaciones',
      'Sube lentamente: piernas, abdomen, pecho, brazos, cabeza',
      'Nota sin juzgar, solo observa',
    ],
    type: 'cuerpo',
  },
  {
    id: 'caminata-consciente',
    name: 'Caminata consciente',
    duration: '10 min',
    description: 'Camina sintiendo cada paso, conectando con el momento.',
    steps: [
      'Busca un espacio para caminar (puede ser pequeño)',
      'Camina más lento de lo normal',
      'Siente cómo el pie toca el suelo',
      'Nota el movimiento de tu cuerpo',
      'Si la mente divaga, vuelve a los pies',
    ],
    type: 'movimiento',
  },
  {
    id: 'pausa-un-minuto',
    name: 'Pausa de un minuto',
    duration: '1 min',
    description: 'Un reset rápido para cualquier momento del día.',
    steps: [
      'Detén lo que estés haciendo',
      'Cierra los ojos',
      'Toma 3 respiraciones profundas',
      'Pregúntate: ¿Cómo estoy ahora?',
      'Abre los ojos suavemente',
    ],
    type: 'pausa',
  },
  {
    id: 'respiracion-box',
    name: 'Respiración cuadrada',
    duration: '4 min',
    description: 'Equilibra tu sistema nervioso con este patrón simple.',
    steps: [
      'Inhala contando hasta 4',
      'Mantén contando hasta 4',
      'Exhala contando hasta 4',
      'Mantén vacío contando hasta 4',
      'Repite 5 veces',
    ],
    type: 'respiracion',
  },
];

export const DAILY_ANCHORS = [
  'Estás acá. Este momento es real.',
  'Respirá. El aire entra y sale.',
  'Volvé al cuerpo. Sentí tus pies.',
  'Este instante es suficiente.',
  'No tenés que resolver nada ahora.',
  'Suavizá los hombros. Aflojá la mandíbula.',
  'Mirá a tu alrededor. ¿Qué ves?',
  'Estás haciendo lo mejor que podés.',
  'Una cosa a la vez.',
  'El pasado ya fue. El futuro vendrá.',
  'Ahora mismo, estás bien.',
  'Permitite esta pausa.',
];

export const GOOD_ACTIONS_SUGGESTIONS = [
  'Escucha a alguien sin interrumpir',
  'Agradece algo específico a alguien',
  'Ayuda a alguien sin que te lo pida',
  'Pide perdón por algo pendiente',
  'Desconéctate del celular por 1 hora',
  'Sonríe a un desconocido',
  'Deja pasar a alguien en la fila',
  'Envía un mensaje positivo a alguien',
  'Recoge algo del suelo en la calle',
  'Ofrece tu asiento a alguien',
  'Prepara algo para otra persona',
  'Llama a alguien que extrañes',
];

export const QUESTIONNAIRE_QUESTIONS = [
  {
    id: 'morning-1',
    category: 'mañana',
    question: '¿Qué es lo primero que haces al despertar?',
    options: [
      { value: 'a', label: 'Revisar el celular', anchor: 'digitales' },
      { value: 'b', label: 'Quedarme en cama un rato más', anchor: 'corporales' },
      { value: 'c', label: 'Levantarme directamente', anchor: null },
      { value: 'd', label: 'Hacer algo para mí (estiramiento, agua, etc.)', anchor: null },
      { value: 'e', label: 'Depende del día', anchor: null },
    ],
  },
  {
    id: 'morning-2',
    category: 'mañana',
    question: '¿Cómo describes tus primeros 30 minutos del día?',
    options: [
      { value: 'a', label: 'Apresurados y automáticos', anchor: 'corporales' },
      { value: 'b', label: 'Tranquilos y con rutina', anchor: null },
      { value: 'c', label: 'Caóticos, sin orden', anchor: 'corporales' },
      { value: 'd', label: 'Conectado con pantallas', anchor: 'digitales' },
      { value: 'e', label: 'Variables según el día', anchor: null },
    ],
  },
  {
    id: 'transitions-1',
    category: 'transiciones',
    question: '¿Qué haces cuando tienes un momento libre inesperado?',
    options: [
      { value: 'a', label: 'Reviso redes o noticias', anchor: 'digitales' },
      { value: 'b', label: 'Como algo aunque no tenga hambre', anchor: 'corporales' },
      { value: 'c', label: 'Busco algo que hacer', anchor: null },
      { value: 'd', label: 'Disfruto el momento', anchor: null },
      { value: 'e', label: 'Me pongo ansioso', anchor: 'corporales' },
    ],
  },
  {
    id: 'transitions-2',
    category: 'transiciones',
    question: '¿Cómo manejas la espera (fila, transporte, etc.)?',
    options: [
      { value: 'a', label: 'Celular inmediatamente', anchor: 'digitales' },
      { value: 'b', label: 'Me impaciento', anchor: 'corporales' },
      { value: 'c', label: 'Observo mi entorno', anchor: null },
      { value: 'd', label: 'Pienso en pendientes', anchor: 'corporales' },
      { value: 'e', label: 'Depende de mi humor', anchor: null },
    ],
  },
  {
    id: 'meals-1',
    category: 'comidas',
    question: '¿Cómo sueles comer?',
    options: [
      { value: 'a', label: 'Rápido y sin prestar atención', anchor: 'corporales' },
      { value: 'b', label: 'Mientras miro algo en pantalla', anchor: 'digitales' },
      { value: 'c', label: 'Con calma y sin distracciones', anchor: null },
      { value: 'd', label: 'Trabajando o haciendo otra cosa', anchor: 'corporales' },
      { value: 'e', label: 'Varía mucho', anchor: null },
    ],
  },
  {
    id: 'breaks-1',
    category: 'pausas',
    question: '¿Tomas pausas durante el día?',
    options: [
      { value: 'a', label: 'Casi nunca', anchor: 'corporales' },
      { value: 'b', label: 'Solo para el celular', anchor: 'digitales' },
      { value: 'c', label: 'Sí, para descansar realmente', anchor: null },
      { value: 'd', label: 'Solo cuando el cuerpo me obliga', anchor: 'corporales' },
      { value: 'e', label: 'Quisiera pero no puedo', anchor: 'corporales' },
    ],
  },
  {
    id: 'social-1',
    category: 'social',
    question: '¿Cómo te sientes en situaciones sociales?',
    options: [
      { value: 'a', label: 'Cómodo y presente', anchor: null },
      { value: 'b', label: 'Ansioso o incómodo', anchor: 'sociales' },
      { value: 'c', label: 'Buscando excusas para salir', anchor: 'sociales' },
      { value: 'd', label: 'Mirando el celular frecuentemente', anchor: 'digitales' },
      { value: 'e', label: 'Depende de con quién', anchor: 'sociales' },
    ],
  },
  {
    id: 'night-1',
    category: 'noche',
    question: '¿Qué haces antes de dormir?',
    options: [
      { value: 'a', label: 'Pantallas hasta el final', anchor: 'digitales' },
      { value: 'b', label: 'Preparo el día siguiente', anchor: null },
      { value: 'c', label: 'Leo o descanso sin pantallas', anchor: null },
      { value: 'd', label: 'Quedo atrapado en pensamientos', anchor: 'corporales' },
      { value: 'e', label: 'Varía mucho', anchor: null },
    ],
  },
  {
    id: 'night-2',
    category: 'noche',
    question: '¿Cómo describes tu calidad de sueño?',
    options: [
      { value: 'a', label: 'Me cuesta dormirme', anchor: 'corporales' },
      { value: 'b', label: 'Duermo pero no descanso', anchor: 'corporales' },
      { value: 'c', label: 'Generalmente bien', anchor: null },
      { value: 'd', label: 'Me despierto varias veces', anchor: 'corporales' },
      { value: 'e', label: 'Irregular', anchor: 'corporales' },
    ],
  },
];

export const FORUM_TOPICS = [
  '¿Qué pequeña cosa te ayudó hoy?',
  '¿Cuál es tu ancla cuando pierdes el foco?',
  '¿Qué aprendiste de un momento difícil?',
  '¿Cómo manejas los pensamientos repetitivos?',
  '¿Qué significa para ti estar presente?',
];

export const REFERENT_MESSAGES = [
  'Hola. Estoy aquí para acompañarte, no para darte respuestas.',
  '¿Cómo estás hoy? Sin juzgar, solo notando.',
  'A veces el progreso no se ve. Pero está.',
  'No tienes que hacerlo perfecto. Solo presente.',
  'Cada día que lo intentas, cuenta.',
];
